### ISSUE TITLE
New oemof structure has to be adapted

### ISSUE THREAD

**Issue by henhuy** [rl-institut/smooth#112]
Omeof has a new structure.
Thus, importing oemof is deprectated. Instead, follwowing packages have to be installed (for smooth, using solph):
- oemof.network
- oemof.solph

Additionally, outputlib has moved into package oemof.solph

**Comment by b-r-u** [comment]
Thanks! Unfortunately, we are stuck with an old version of oemof until https://github.com/oemof/oemof-solph/pull/592 is resolved.

https://github.com/rl-institut/smooth/blob/07e072c72b7f634d30b060188961b42d13c081c2/.travis.yml#L12-L17

**Comment by henhuy** [comment]
Alright!
