### ISSUE TITLE
Wrong license stated in setup.py

### ISSUE THREAD

**Issue by stefansc1** [rl-institut/smooth#153]
The setup.py still lists GNU AGPL v3 as our license. In reality, it is dual-license MIT/Apache-2.0.

**Comment by morrme** [comment]
Do you want [this line ](https://github.com/rl-institut/smooth/blob/dev/setup.py#L9)to just say "Dual-License MIT/Apache-2.0" ?

Should there be a date? And does this get pushed to `dev`?

**Comment by stefansc1** [comment]
That's the correct line. I would leave the date out. Please read our [contributing guidelines](https://github.com/rl-institut/smooth/blob/dev/CONTRIBUTING.md).
