### ISSUE TITLE
master branch is out-of-date

### ISSUE THREAD

**Issue by b-r-u** [rl-institut/smooth#198]
The master branch is nearly a year old and does not serve any purpose. I propose merging the dev branch and continue development on the master-branch. At our current rate of development we don't have a useful stable baseline. If we want to support older versions of smooth in the future, we can create dedicated branches for that. 

Using the master branch we can also use the standard URL for readthedocs, ending with `latest`.

Some context: https://softwareengineering.stackexchange.com/questions/312022/the-trend-of-the-develop-branch-going-away

**Comment by b-r-u** [comment]
That part about readthedocs was wrong. I just pointed the dev branch to `latest`:

https://smooth.readthedocs.io/en/latest/

**Comment by j-brendel** [comment]
Master branch is now up to date with version 0.3.0
