### ISSUE TITLE
There are no emissions in each components

### ISSUE THREAD

**Issue by LauWien** [rl-institut/smooth#2]

**Comment by j-ti** [comment]
emissions could be treated as
1. variable_emissions (independently from cost) which I do currently
or
2. emissions_cost (artificial cost) -> would need a factor to balance between emissions[kg] and cost [EUR]
which one should be realized? @LauWien

**Comment by j-ti** [comment]
>     1. variable_emissions (independently from cost) which I do currently (commit [7d42326](https://github.com/rl-institut/smooth/commit/7d423269cb9cc8d49d5ef63aadfbac57e7c05f5f))

Together with Laura, we decided to keep it as variable_emissions [g/Wh] and, for now, keep the calculation in component.update_cost() next to the calculation of variable_costs [EUR/Wh]

**Comment by j-ti** [comment]
commit 76efe6dbd52473c2fe905ac3c12f6b86c05ed511 
- emissions are now in [kg]
- variable name change cap_emissions to fix_emissions
- update emissions in a seperate function from cost

**Comment by j-ti** [comment]
https://github.com/rl-institut/smooth/pull/15
