### ISSUE TITLE
Battery Component profits from simultaneous in- and outflow

### ISSUE THREAD

**Issue by j-brendel** [rl-institut/smooth#218]
Because of the usage of niominal value in the P_max_in and P_max_out definitions, the battery can't be used for MPC Simulations.

Idea:
Silmlify  with Nominal Value for MPC compliance.

For Coherence updated Component should have these properties:

- Discharge and Charge Symmetrical
![grafik](https://user-images.githubusercontent.com/39203376/101789366-85291400-3b01-11eb-8c5a-5595ad6c639b.png)
![grafik](https://user-images.githubusercontent.com/39203376/101789485-a558d300-3b01-11eb-860a-3f6def82bdd1.png)

- keep 100 % possible
![grafik](https://user-images.githubusercontent.com/39203376/101789584-c5889200-3b01-11eb-9e48-c18eb374a8d5.png)

- Same behaviour 1 min and 60 min interval time

![grafik](https://user-images.githubusercontent.com/39203376/101789366-85291400-3b01-11eb-8c5a-5595ad6c639b.png)
![grafik](https://user-images.githubusercontent.com/39203376/101789760-f49f0380-3b01-11eb-876f-d70f309e8e61.png)

**Comment by j-ti** [comment]
With the correct loss rate and efficientcy coefficients, eomof handels everything on its own and correctly.

The reason for the constant loading in #212 appears when -vac_in <= vac_out and -vac_in > variable grid cost, as it oemof does not distinguish between artificial or normal costs and makes profits from high inflow (negative cost) although outflow with equal vac as there is energy loss on in and out flow  (e. g. 100 Ah * 0.95 * 0.95 = 90.25 Ah). As energy flowing out is less, than inflow, even equal +/-vac results in a net negative value.

=> vac_in and vac_out should always be below the grid costs.

**Comment by j-brendel** [comment]
With these changes, only one consistency criteroin is broken: 
Charging and discharging are not symmetrical:
![grafik](https://user-images.githubusercontent.com/39203376/102108595-698c7900-3e33-11eb-8625-273a3ef039a9.png)
![grafik](https://user-images.githubusercontent.com/39203376/102108615-6ee9c380-3e33-11eb-9608-531b1ce658e5.png)

Could we modify max_power in battery component to:

        self.p_in_max = self.c_rate_charge * self.battery_capacity / self.efficiency_charge
        self.p_out_max = self.c_rate_discharge * self.battery_capacity * self.efficiency_discharge

This solves this issue, do you think it creates others?

![grafik](https://user-images.githubusercontent.com/39203376/102108766-980a5400-3e33-11eb-88ab-5a62b07d7b66.png)
![grafik](https://user-images.githubusercontent.com/39203376/102108781-9fc9f880-3e33-11eb-9e34-5541a12f44f3.png)

I used these files to create plots for consistency checks:
[example_Battery.zip](https://github.com/rl-institut/smooth/files/5690254/example_Battery.zip)

**Comment by j-ti** [comment]
https://github.com/rl-institut/smooth/issues/212#issuecomment-742537429

**Comment by j-ti** [comment]
PR  #223 was merged containing the new maximum nominal power definition

**Comment by j-brendel** [comment]
Solved with #261
