### ISSUE TITLE
Battery definition for depth of discharge (dod) is confused with SOC_min

### ISSUE THREAD

**Issue by j-ti** [rl-institut/smooth#219]
dod = 0.2 means 20% were discharged from a full battery, whereas
soc_min = 0.2 means the battery is charged by 20%

**Comment by j-brendel** [comment]
So you propose it should be renamed from dod to soc_min, right? The implementaion however is correct?

**Comment by j-ti** [comment]
Decision from Meeting: change to soc_min, raise key error for dod with notification that attribute name was changed, but value meaning stays minimal_storage_level
