### ISSUE TITLE
setup.py does not work due to readme.md

### ISSUE THREAD

**Issue by j-brendel** [rl-institut/smooth#224]
![grafik](https://user-images.githubusercontent.com/39203376/104300352-a7c69800-54c6-11eb-9b8a-9efcd0be753d.png)

I locally removed the line 

    long_description=open('README.md').read(),

from setup.py, now it works. But I don't see the problem in README.md

**Comment by b-r-u** [comment]
It's a decoding error that is triggered by these fancy quote characters `“”` in `README.md`. The file is valid UTF-8, but `setup.py` tries [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) in your case.

We could replace them with non-fancy double quotes `"` and also specify the encoding in the `open` call:
```python
open("README.md", encoding="utf-8").read()
```
