### ISSUE TITLE
smooth\tests\test_optimization.py is finding errors

### ISSUE THREAD

**Issue by j-brendel** [rl-institut/smooth#226]
![grafik](https://user-images.githubusercontent.com/39203376/104446735-2d1b7c80-559b-11eb-8480-97bb2d9fc533.png)

When running  'pytest tests' I get
ModuleNotFoundError: No module named 'oemof'

Is this only true for me?

**Comment by b-r-u** [comment]
Try running `pip install -r requirements.txt` in your virtual environment. This should install the specific version of oemof we need.

**Comment by j-brendel** [comment]
Thanks for the hint, that did the trick!
