### ISSUE TITLE
oemof PR is gone, installation fails

### ISSUE THREAD

**Issue by b-r-u** [rl-institut/smooth#65]
This PR for the oemof repo is gone: https://github.com/oemof/oemof/pull/592
It's needed for the installtion of smooth (see [README](https://github.com/rl-institut/smooth/blob/28b300dc54da5f1be8e12cbc9932406333f79faf/README.md)), so all travis builds will fail for now.

**Comment by j-ti** [comment]
repository was rename(see https://github.com/oemof/oemof/issues/58):
PR can now be found at https://github.com/oemof/oemof-solph/pulls/592

**Comment by b-r-u** [comment]
I'm relieved!
