### ISSUE TITLE
MATLAB-haruspex function is missing in python

### ISSUE THREAD

**Issue by LauWien** [rl-institut/smooth#7]

**Comment by j-ti** [comment]
primary goals
- output timestep of error
- output states of components until timestep of error

**Comment by j-ti** [comment]
[debugDataframe.txt](https://github.com/rl-institut/smooth/files/4197398/debugDataframe.txt)
![infeasable_model](https://user-images.githubusercontent.com/56872869/74419632-85597400-4e4a-11ea-9d0c-8fef343c2f0d.png)

**Comment by j-ti** [comment]
currently debugging function will automatically be executed when optimization status is not ok and termination condition is not optimal and raise a runtime exception 
1. should it continue running when termination condition is not optimal but there are supoptimal flows generated?
2. should it be changed, so it will execute the debugging function only manually
