### ISSUE TITLE
Relicense under dual MIT / Apache v2

### ISSUE THREAD

**Issue by b-r-u** [rl-institut/smooth#95]
We would like to relicense this repo to MIT / Apache v2.

To agree to relicensing, comment with :
```
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.
```

* [x] @SpamAndEgg
* [x] @b-r-u
* [x] @ciaradunks
* [x] @j-ti
* [x] @jakobgemassmer
* [x] @LauWien
* [x] @stefansc1
* [x] @timroepcke
* [x] @ulrikeherrmann

**Comment by b-r-u** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

**Comment by timroepcke** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

**Comment by SpamAndEgg** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

**Comment by ciaradunks** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

**Comment by jakobgemassmer** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.

**Comment by j-ti** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license,
allowing licensees to chose either at their option.
